# items.py
items = {
    "Vegetables": [
        {'id': 1, 'name': 'Onion (red)'},
        {'id': 2, 'name': 'Onion (white)'},
        {'id': 3, 'name': 'Cilantro'},
        {'id': 4, 'name': 'Mint Leaf'},
        {'id': 5, 'name': 'Bell Pepper'},
        {'id': 6, 'name': 'Ring Onion (Green Onion)'},
        {'id': 7, 'name': 'Beet Root'},
        {'id': 8, 'name': 'Garlic'}
    ],
    "Oils and Spices": [
        {'id': 9, 'name': 'SoyaBean Oil'},
        {'id': 10, 'name': 'Fry Oil'},
        {'id': 11, 'name': 'Sugar'},
        {'id': 12, 'name': 'Salt'},
        {'id': 13, 'name': 'Pan Release Spray'},
        {'id': 14, 'name': 'Tomato Puree'},
        {'id': 15, 'name': 'Fruit Punch Drink Base'},
        {'id': 16, 'name': 'Lemonade Drink Base'},
        {'id': 17, 'name': 'Lemon Yellow Food Colour'},
        {'id': 18, 'name': 'Soy Sauce'},
        {'id': 19, 'name': 'Royal Basmati Rice'},
        {'id': 20, 'name': 'White Rice (Extra Large Grain)'}
    ],
    "Dairy and Bakery": [
        {'id': 21, 'name': 'All Purpose Flour'},
        {'id': 22, 'name': 'Chocolate Syrup'},
        {'id': 23, 'name': 'Caramel Syrup'},
        {'id': 24, 'name': 'Corn Starch'},
        {'id': 25, 'name': 'Liquid Margarine'},
        {'id': 26, 'name': 'Puff Sheet'},
        {'id': 27, 'name': 'Dry Chilli'},
        {'id': 28, 'name': 'Coffee Beans'},
        {'id': 29, 'name': 'Raw Sugar'},
        {'id': 30, 'name': 'Pure Cane Sugar'},
        {'id': 31, 'name': 'Splenda'},
        {'id': 32, 'name': 'Vegetable Shortening'},
        {'id': 33, 'name': 'Ketchup'},
        {'id': 34, 'name': 'Garbanzo [Channa]'},
        {'id': 35, 'name': 'Paneer'},
        {'id': 36, 'name': 'Butter'},
        {'id': 37, 'name': 'Cheese'},
        {'id': 38, 'name': 'Yogurt'},
        {'id': 39, 'name': 'Milk Cream'},
        {'id': 40, 'name': 'Milk'}
    ],
    "Household Supplies": [
        {'id': 41, 'name': 'Wax paper'},
        {'id': 42, 'name': 'Fabuloso'},
        {'id': 43, 'name': 'Clorox'},
        {'id': 44, 'name': 'Stainless Steel Scrub'},
        {'id': 45, 'name': 'Surface Liquid'},
        {'id': 46, 'name': 'HILITE soap'}
    ],
    "Packaging Supplies": [
        {'id': 47, 'name': 'Water Bottle'},
        {'id': 48, 'name': 'Candy'},
        {'id': 49, 'name': 'Medium Bag'},
        {'id': 50, 'name': 'Big Bag'},
        {'id': 51, 'name': 'Small Bag'},
        {'id': 52, 'name': '3.25 oz container'},
        {'id': 53, 'name': '4 oz container'},
        {'id': 54, 'name': '3.25 oz & 4 oz Lids'},
        {'id': 55, 'name': '9 x 9 Dosa Box'},
        {'id': 56, 'name': '9 x 6 Parota box'},
        {'id': 57, 'name': '6 x 6 Idli Box'},
        {'id': 58, 'name': '16 oz Round Box'},
        {'id': 59, 'name': '24 oz Square Box'},
        {'id': 60, 'name': '28 oz Square Box'},
        {'id': 61, 'name': 'Foil (18 x 1000)'},
        {'id': 62, 'name': 'Plastic Spoon'},
        {'id': 63, 'name': 'Plastic Fork'},
        {'id': 64, 'name': 'Plastic Knife'},
        {'id': 65, 'name': 'Sipper Straw'},
        {'id': 66, 'name': 'Mango Lassi Cup (12 oz)'},
        {'id': 67, 'name': 'Mango Lassi Cup (9 oz)'},
        {'id': 68, 'name': 'Lassi Cup lids'},
        {'id': 69, 'name': 'Paper Straw big'},
        {'id': 70, 'name': 'Paper Straw Small'},
        {'id': 71, 'name': 'Coffee Cups (8 oz)'},
        {'id': 72, 'name': 'Coffee cup Lids'},
        {'id': 73, 'name': 'Dinner Napkins'},
        {'id': 74, 'name': '2 oz Cups'},
        {'id': 75, 'name': '2 oz Lids'},
        {'id': 76, 'name': 'Water Cups'},
        {'id': 77, 'name': 'Gloves (Medium, Large Size)'},
        {'id': 78, 'name': 'Sanitizer'}
    ],
    "Trays and Lids": [
        {'id': 79, 'name': '4" Full Trays'},
        {'id': 80, 'name': '4" Half Trays'},
        {'id': 81, 'name': '2" Full Trays'},
        {'id': 82, 'name': '2" Half Trays'},
        {'id': 83, 'name': 'Full Tray Lids'},
        {'id': 84, 'name': 'Half Tray Lids'}
    ]
}
